import esbuild from 'esbuild';
import process from 'process';
import { builtinModules } from 'node:module';

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === 'production';

// pdf.js's worker must run as a real, isolated Web Worker — not the
// 'globalThis.pdfjsWorker' fake-main-thread-worker hack — because Obsidian's
// native PDF viewer bundles its own (different-versioned) copy of pdfjs-dist
// and reads that same global. Sharing it causes the native viewer to either
// break immediately or permanently memoize our worker handler the first time
// it happens to observe it (pdf.js caches that decision for the process
// lifetime). We can't ship the worker as a sibling file either: whatever dev
// deploy tooling copies this plugin into the vault only syncs main.js,
// manifest.json and styles.css, so any extra file we emit never reaches the
// installed plugin folder. Instead we bundle the worker to a string and embed
// it directly inside main.js; at runtime we turn that string into a Blob URL,
// which still gives pdf.js a fully separate, real Worker thread.
const workerBuild = await esbuild.build({
	entryPoints: ['node_modules/pdfjs-dist/build/pdf.worker.mjs'],
	bundle: true,
	format: 'esm',
	target: 'es2021',
	logLevel: 'info',
	treeShaking: true,
	minify: prod,
	platform: 'browser',
	write: false,
});
const pdfWorkerSource = workerBuild.outputFiles[0].text;

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ['src/main.ts'],
	bundle: true,
	external: [
		'obsidian',
		'electron',
		// vectra's TransformersEmbeddings lazily requires this for local ONNX embeddings,
		// a code path we never use (we only use GeminiEmbeddings) — mark external so esbuild
		// doesn't try to bundle a dependency we intentionally removed.
		'@huggingface/transformers',
		'@codemirror/autocomplete',
		'@codemirror/collab',
		'@codemirror/commands',
		'@codemirror/language',
		'@codemirror/lint',
		'@codemirror/search',
		'@codemirror/state',
		'@codemirror/view',
		'@lezer/common',
		'@lezer/highlight',
		'@lezer/lr',
		...builtinModules,
		...builtinModules.map((m) => `node:${m}`),
	],
	format: 'cjs',
	target: 'es2021',
	logLevel: 'info',
	sourcemap: prod ? false : 'inline',
	treeShaking: true,
	outfile: 'main.js',
	minify: prod,
	platform: 'browser',
	define: {
		__PDF_WORKER_SOURCE__: JSON.stringify(pdfWorkerSource),
	},
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
